# Set new leader/prefix
unbind C-Space

set -g prefix C-Space
bind C-Space send-prefix

# Pane Splitting
bind    "|"     split-window -h   -c "#{pane_current_path}"
bind    "\\"    split-window -fh  -c "${pane_current_path}" 

bind    "-"     split-window -v   -c "#{pane_current_path}"
bind    "_"     split-window -fv  -c "${pane_current_path}" 

bind    r       source-file ~/.tmux.conf

set -g status on
set -g status-position top
set -g status-left "#(whoami)@#H"
set -g status-right "#(date '+%Y-%m-%d %H:%M')"
